// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ContainerInfo struct {
	Id        int64   `json:"id"`
	Number    string  `json:"number"`
	YardId    int64   `json:"yardId"`
	Longitude float64 `json:"longitude"`
	Latitude  float64 `json:"latitude"`
	Distance  float64 `json:"distance"`
}

type MapQueryReq struct {
	Longitude float64 `form:"longitude"`
	Latitude  float64 `form:"latitude"`
	Radius    float64 `form:"radius"`
	MinLon    float64 `form:"minLon,optional"`
	MaxLon    float64 `form:"maxLon,optional"`
	MinLat    float64 `form:"minLat,optional"`
	MaxLat    float64 `form:"maxLat,optional"`
}

type MapQueryResp struct {
	Yards      []YardInfo      `json:"yards"`
	Containers []ContainerInfo `json:"containers"`
}

type YardInfo struct {
	Id        int64   `json:"id"`
	Name      string  `json:"name"`
	Longitude float64 `json:"longitude"`
	Latitude  float64 `json:"latitude"`
	Distance  float64 `json:"distance"`
}
