// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package vipplans

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	vipPlansFieldNames          = builder.RawFieldNames(&VipPlans{})
	vipPlansRows                = strings.Join(vipPlansFieldNames, ",")
	vipPlansRowsExpectAutoSet   = strings.Join(stringx.Remove(vipPlansFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	vipPlansRowsWithPlaceHolder = strings.Join(stringx.Remove(vipPlansFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	vipPlansModel interface {
		Insert(ctx context.Context, data *VipPlans) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*VipPlans, error)
		FindOneBySlug(ctx context.Context, slug sql.NullString) (*VipPlans, error)
		Update(ctx context.Context, data *VipPlans) error
		Delete(ctx context.Context, id int64) error
	}

	defaultVipPlansModel struct {
		conn  sqlx.SqlConn
		table string
	}

	VipPlans struct {
		Id                             int64           `db:"id"`
		Name                           string          `db:"name"`
		NameEn                         string          `db:"name_en"`
		Features                       string          `db:"features"`
		FeaturesEn                     string          `db:"features_en"`
		Price                          float64         `db:"price"`
		Days                           int64           `db:"days"`
		RoleIds                        string          `db:"role_ids"`
		Status                         int64           `db:"status"`
		CreatedAt                      time.Time       `db:"created_at"`
		UpdatedAt                      time.Time       `db:"updated_at"`
		Description                    sql.NullString  `db:"description"`
		DescriptionEn                  sql.NullString  `db:"description_en"`
		Position                       int64           `db:"position"`
		PriceDescription               sql.NullString  `db:"price_description"`
		PriceDescriptionEn             sql.NullString  `db:"price_description_en"`
		DaysDescription                sql.NullString  `db:"days_description"`
		DaysDescriptionEn              sql.NullString  `db:"days_description_en"`
		AccountCount                   int64           `db:"account_count"`
		Discount                       sql.NullFloat64 `db:"discount"`
		PaymentPeriod                  sql.NullInt64   `db:"payment_period"`
		Meta                           string          `db:"meta"`
		Slug                           sql.NullString  `db:"slug"`
		MembershipKind                 sql.NullString  `db:"membership_kind"`
		MonthlyPrice                   sql.NullFloat64 `db:"monthly_price"`
		AnnualPrice                    sql.NullFloat64 `db:"annual_price"`
		PermissionNames                string          `db:"permission_names"`
		MaxLeasingIncompleteContainers sql.NullInt64   `db:"max_leasing_incomplete_containers"`
	}
)

func newVipPlansModel(conn sqlx.SqlConn) *defaultVipPlansModel {
	return &defaultVipPlansModel{
		conn:  conn,
		table: "`vip_plans`",
	}
}

func (m *defaultVipPlansModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultVipPlansModel) FindOne(ctx context.Context, id int64) (*VipPlans, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", vipPlansRows, m.table)
	var resp VipPlans
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVipPlansModel) FindOneBySlug(ctx context.Context, slug sql.NullString) (*VipPlans, error) {
	var resp VipPlans
	query := fmt.Sprintf("select %s from %s where `slug` = ? limit 1", vipPlansRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, slug)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultVipPlansModel) Insert(ctx context.Context, data *VipPlans) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, vipPlansRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.NameEn, data.Features, data.FeaturesEn, data.Price, data.Days, data.RoleIds, data.Status, data.Description, data.DescriptionEn, data.Position, data.PriceDescription, data.PriceDescriptionEn, data.DaysDescription, data.DaysDescriptionEn, data.AccountCount, data.Discount, data.PaymentPeriod, data.Meta, data.Slug, data.MembershipKind, data.MonthlyPrice, data.AnnualPrice, data.PermissionNames, data.MaxLeasingIncompleteContainers)
	return ret, err
}

func (m *defaultVipPlansModel) Update(ctx context.Context, newData *VipPlans) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, vipPlansRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Name, newData.NameEn, newData.Features, newData.FeaturesEn, newData.Price, newData.Days, newData.RoleIds, newData.Status, newData.Description, newData.DescriptionEn, newData.Position, newData.PriceDescription, newData.PriceDescriptionEn, newData.DaysDescription, newData.DaysDescriptionEn, newData.AccountCount, newData.Discount, newData.PaymentPeriod, newData.Meta, newData.Slug, newData.MembershipKind, newData.MonthlyPrice, newData.AnnualPrice, newData.PermissionNames, newData.MaxLeasingIncompleteContainers, newData.Id)
	return err
}

func (m *defaultVipPlansModel) tableName() string {
	return m.table
}
