// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package membershippurchases

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	membershipPurchasesFieldNames          = builder.RawFieldNames(&MembershipPurchases{})
	membershipPurchasesRows                = strings.Join(membershipPurchasesFieldNames, ",")
	membershipPurchasesRowsExpectAutoSet   = strings.Join(stringx.Remove(membershipPurchasesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	membershipPurchasesRowsWithPlaceHolder = strings.Join(stringx.Remove(membershipPurchasesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	membershipPurchasesModel interface {
		Insert(ctx context.Context, data *MembershipPurchases) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MembershipPurchases, error)
		FindOneByOrderId(ctx context.Context, orderId sql.NullInt64) (*MembershipPurchases, error)
		Update(ctx context.Context, data *MembershipPurchases) error
		Delete(ctx context.Context, id int64) error
	}

	defaultMembershipPurchasesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	MembershipPurchases struct {
		Id                             int64         `db:"id"`
		CompanyId                      int64         `db:"company_id"`
		UserId                         int64         `db:"user_id"`
		VipPlanId                      int64         `db:"vip_plan_id"`
		OrderId                        sql.NullInt64 `db:"order_id"`
		BillingPeriod                  string        `db:"billing_period"`
		Price                          float64       `db:"price"`
		StartsAt                       time.Time     `db:"starts_at"`
		ExpiresAt                      time.Time     `db:"expires_at"`
		Source                         string        `db:"source"`
		Status                         string        `db:"status"`
		PermissionNames                string        `db:"permission_names"`
		RoleIds                        string        `db:"role_ids"`
		ExpiryReminderSentAt           sql.NullTime  `db:"expiry_reminder_sent_at"`
		Meta                           string        `db:"meta"`
		CreatedAt                      time.Time     `db:"created_at"`
		UpdatedAt                      time.Time     `db:"updated_at"`
		MaxLeasingIncompleteContainers sql.NullInt64 `db:"max_leasing_incomplete_containers"`
		ActivationMethod               string        `db:"activation_method"`
		DeletedAt                      sql.NullTime  `db:"deleted_at"`
	}
)

func newMembershipPurchasesModel(conn sqlx.SqlConn) *defaultMembershipPurchasesModel {
	return &defaultMembershipPurchasesModel{
		conn:  conn,
		table: "`membership_purchases`",
	}
}

func (m *defaultMembershipPurchasesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMembershipPurchasesModel) FindOne(ctx context.Context, id int64) (*MembershipPurchases, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", membershipPurchasesRows, m.table)
	var resp MembershipPurchases
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMembershipPurchasesModel) FindOneByOrderId(ctx context.Context, orderId sql.NullInt64) (*MembershipPurchases, error) {
	var resp MembershipPurchases
	query := fmt.Sprintf("select %s from %s where `order_id` = ? limit 1", membershipPurchasesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, orderId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMembershipPurchasesModel) Insert(ctx context.Context, data *MembershipPurchases) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, membershipPurchasesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CompanyId, data.UserId, data.VipPlanId, data.OrderId, data.BillingPeriod, data.Price, data.StartsAt, data.ExpiresAt, data.Source, data.Status, data.PermissionNames, data.RoleIds, data.ExpiryReminderSentAt, data.Meta, data.MaxLeasingIncompleteContainers, data.ActivationMethod, data.DeletedAt)
	return ret, err
}

func (m *defaultMembershipPurchasesModel) Update(ctx context.Context, newData *MembershipPurchases) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, membershipPurchasesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.CompanyId, newData.UserId, newData.VipPlanId, newData.OrderId, newData.BillingPeriod, newData.Price, newData.StartsAt, newData.ExpiresAt, newData.Source, newData.Status, newData.PermissionNames, newData.RoleIds, newData.ExpiryReminderSentAt, newData.Meta, newData.MaxLeasingIncompleteContainers, newData.ActivationMethod, newData.DeletedAt, newData.Id)
	return err
}

func (m *defaultMembershipPurchasesModel) tableName() string {
	return m.table
}
