// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"map-server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.SignatureMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/api/tradings/list",
					Handler: GetTradingsListHandler(serverCtx),
				},
			}...,
		),
	)
}
