// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package companies

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	companiesFieldNames          = builder.RawFieldNames(&Companies{})
	companiesRows                = strings.Join(companiesFieldNames, ",")
	companiesRowsExpectAutoSet   = strings.Join(stringx.Remove(companiesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	companiesRowsWithPlaceHolder = strings.Join(stringx.Remove(companiesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	companiesModel interface {
		Insert(ctx context.Context, data *Companies) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Companies, error)
		Update(ctx context.Context, data *Companies) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCompaniesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Companies struct {
		Id                        int64          `db:"id"`
		Name                      sql.NullString `db:"name"`
		LocationId                sql.NullInt64  `db:"location_id"`
		Telephone                 sql.NullString `db:"telephone"`
		CreatedAt                 time.Time      `db:"created_at"`
		UpdatedAt                 time.Time      `db:"updated_at"`
		Email                     sql.NullString `db:"email"` // 企业邮箱
		Usci                      sql.NullString `db:"usci"`  // UNIFIED SOCIAL CREDIT IDENTIFIER, 统一社会信用代码
		UserId                    sql.NullInt64  `db:"user_id"`
		Status                    int64          `db:"status"`
		VerifyMethod              sql.NullInt64  `db:"verify_method"`
		FirstName                 sql.NullString `db:"first_name"`
		LastName                  sql.NullString `db:"last_name"`
		ReviewLevel               float64        `db:"review_level"`
		ReviewsCount              int64          `db:"reviews_count"`
		PaymentPassword           sql.NullString `db:"payment_password"`
		AuditStatus               int64          `db:"audit_status"`
		FollowersCount            int64          `db:"followers_count"`
		TradingsCount             int64          `db:"tradings_count"`
		LeasingsCount             int64          `db:"leasings_count"`
		TradingDemandsCount       int64          `db:"trading_demands_count"`
		LeasingDemandsCount       int64          `db:"leasing_demands_count"`
		TradingSuppliesCount      int64          `db:"trading_supplies_count"`
		LeasingSuppliesCount      int64          `db:"leasing_supplies_count"`
		PaymentPasswordErrorCount int64          `db:"payment_password_error_count"`
		LevelId                   sql.NullInt64  `db:"level_id"`
		IsOfficial                int64          `db:"is_official"`
		IsQuickResponse           int64          `db:"is_quick_response"`
		InvoiceIndex              int64          `db:"invoice_index"`
		Address                   sql.NullString `db:"address"`
		BusinessTypes             string         `db:"business_types"`  // 公司主要经营类型
		MainIntentions            string         `db:"main_intentions"` // 主要交易意向
		Position                  sql.NullString `db:"position"`        // 职位
		DealsCount                int64          `db:"deals_count"`
		NegotiationsCount         int64          `db:"negotiations_count"`
		FavoritesCount            int64          `db:"favorites_count"`
		AddressLine1              sql.NullString `db:"address_line1"`
		AddressLine2              sql.NullString `db:"address_line2"`
		PaymentPasswordUpdatedAt  sql.NullTime   `db:"payment_password_updated_at"`
		Meta                      sql.NullString `db:"meta"`
		IsPlatformEscrow          int64          `db:"is_platform_escrow"` // 是否为平台主体公司（钱包与转账规则）
		DeletedAt                 sql.NullTime   `db:"deleted_at"`
		TelephoneCountryCode      sql.NullString `db:"telephone_country_code"`
		TelephoneNumber           sql.NullString `db:"telephone_number"`
	}
)

func newCompaniesModel(conn sqlx.SqlConn) *defaultCompaniesModel {
	return &defaultCompaniesModel{
		conn:  conn,
		table: "`companies`",
	}
}

func (m *defaultCompaniesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCompaniesModel) FindOne(ctx context.Context, id int64) (*Companies, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", companiesRows, m.table)
	var resp Companies
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCompaniesModel) Insert(ctx context.Context, data *Companies) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, companiesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.LocationId, data.Telephone, data.Email, data.Usci, data.UserId, data.Status, data.VerifyMethod, data.FirstName, data.LastName, data.ReviewLevel, data.ReviewsCount, data.PaymentPassword, data.AuditStatus, data.FollowersCount, data.TradingsCount, data.LeasingsCount, data.TradingDemandsCount, data.LeasingDemandsCount, data.TradingSuppliesCount, data.LeasingSuppliesCount, data.PaymentPasswordErrorCount, data.LevelId, data.IsOfficial, data.IsQuickResponse, data.InvoiceIndex, data.Address, data.BusinessTypes, data.MainIntentions, data.Position, data.DealsCount, data.NegotiationsCount, data.FavoritesCount, data.AddressLine1, data.AddressLine2, data.PaymentPasswordUpdatedAt, data.Meta, data.IsPlatformEscrow, data.DeletedAt, data.TelephoneCountryCode, data.TelephoneNumber)
	return ret, err
}

func (m *defaultCompaniesModel) Update(ctx context.Context, data *Companies) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, companiesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.LocationId, data.Telephone, data.Email, data.Usci, data.UserId, data.Status, data.VerifyMethod, data.FirstName, data.LastName, data.ReviewLevel, data.ReviewsCount, data.PaymentPassword, data.AuditStatus, data.FollowersCount, data.TradingsCount, data.LeasingsCount, data.TradingDemandsCount, data.LeasingDemandsCount, data.TradingSuppliesCount, data.LeasingSuppliesCount, data.PaymentPasswordErrorCount, data.LevelId, data.IsOfficial, data.IsQuickResponse, data.InvoiceIndex, data.Address, data.BusinessTypes, data.MainIntentions, data.Position, data.DealsCount, data.NegotiationsCount, data.FavoritesCount, data.AddressLine1, data.AddressLine2, data.PaymentPasswordUpdatedAt, data.Meta, data.IsPlatformEscrow, data.DeletedAt, data.TelephoneCountryCode, data.TelephoneNumber, data.Id)
	return err
}

func (m *defaultCompaniesModel) tableName() string {
	return m.table
}
