// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package depots

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	depotsFieldNames          = builder.RawFieldNames(&Depots{})
	depotsRows                = strings.Join(depotsFieldNames, ",")
	depotsRowsExpectAutoSet   = strings.Join(stringx.Remove(depotsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	depotsRowsWithPlaceHolder = strings.Join(stringx.Remove(depotsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	depotsModel interface {
		Insert(ctx context.Context, data *Depots) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Depots, error)
		Update(ctx context.Context, data *Depots) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDepotsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Depots struct {
		Id                  int64           `db:"id"`
		Name                sql.NullString  `db:"name"`
		PostalCode          sql.NullString  `db:"postal_code"`
		Website             sql.NullString  `db:"website"`
		PhoneNumber         sql.NullString  `db:"phone_number"`
		City                sql.NullString  `db:"city"`
		Country             sql.NullString  `db:"country"`
		ContactName         sql.NullString  `db:"contact_name"`
		Email               sql.NullString  `db:"email"`
		LocationId          sql.NullInt64   `db:"location_id"`
		LocalName           sql.NullString  `db:"local_name"`
		LocalAddress        sql.NullString  `db:"local_address"`
		Language            sql.NullString  `db:"language"`
		Source              sql.NullString  `db:"source"`
		AddressLine1        sql.NullString  `db:"address_line1"`
		AddressLine2        sql.NullString  `db:"address_line2"`
		CreatedAt           time.Time       `db:"created_at"`
		UpdatedAt           time.Time       `db:"updated_at"`
		CompanyId           sql.NullInt64   `db:"company_id"`
		UserId              sql.NullInt64   `db:"user_id"`
		Extra               sql.NullString  `db:"extra"`
		Lat                 sql.NullFloat64 `db:"lat"`
		Lng                 sql.NullFloat64 `db:"lng"`
		OpeningHours        sql.NullString  `db:"opening_hours"`
		HasRepair           int64           `db:"has_repair"`
		EquipmentTypes      string          `db:"equipment_types"`
		UniqueNumber        sql.NullString  `db:"unique_number"`
		Capacity            int64           `db:"capacity"`
		Services            sql.NullString  `db:"services"`
		Level               sql.NullInt64   `db:"level"`
		ContainerCategories sql.NullString  `db:"container_categories"`
		ReviewsCount        int64           `db:"reviews_count"`
		ReservationEnabled  int64           `db:"reservation_enabled"`
		MinimumStorageDays  sql.NullInt64   `db:"minimum_storage_days"`
		CleaningFee         sql.NullFloat64 `db:"cleaning_fee"`
		RepairFee           sql.NullFloat64 `db:"repair_fee"`
		TowingFee           sql.NullFloat64 `db:"towing_fee"`
		OverdueStorageFee   sql.NullFloat64 `db:"overdue_storage_fee"`
		HazardousSurcharge  sql.NullFloat64 `db:"hazardous_surcharge"`
		SpecialHandlingFee  sql.NullFloat64 `db:"special_handling_fee"`
		ReviewLevel         int64           `db:"review_level"`
		Meta                string          `db:"meta"`
	}
)

func newDepotsModel(conn sqlx.SqlConn) *defaultDepotsModel {
	return &defaultDepotsModel{
		conn:  conn,
		table: "`depots`",
	}
}

func (m *defaultDepotsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDepotsModel) FindOne(ctx context.Context, id int64) (*Depots, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", depotsRows, m.table)
	var resp Depots
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDepotsModel) Insert(ctx context.Context, data *Depots) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, depotsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.PostalCode, data.Website, data.PhoneNumber, data.City, data.Country, data.ContactName, data.Email, data.LocationId, data.LocalName, data.LocalAddress, data.Language, data.Source, data.AddressLine1, data.AddressLine2, data.CompanyId, data.UserId, data.Extra, data.Lat, data.Lng, data.OpeningHours, data.HasRepair, data.EquipmentTypes, data.UniqueNumber, data.Capacity, data.Services, data.Level, data.ContainerCategories, data.ReviewsCount, data.ReservationEnabled, data.MinimumStorageDays, data.CleaningFee, data.RepairFee, data.TowingFee, data.OverdueStorageFee, data.HazardousSurcharge, data.SpecialHandlingFee, data.ReviewLevel, data.Meta)
	return ret, err
}

func (m *defaultDepotsModel) Update(ctx context.Context, data *Depots) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, depotsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.PostalCode, data.Website, data.PhoneNumber, data.City, data.Country, data.ContactName, data.Email, data.LocationId, data.LocalName, data.LocalAddress, data.Language, data.Source, data.AddressLine1, data.AddressLine2, data.CompanyId, data.UserId, data.Extra, data.Lat, data.Lng, data.OpeningHours, data.HasRepair, data.EquipmentTypes, data.UniqueNumber, data.Capacity, data.Services, data.Level, data.ContainerCategories, data.ReviewsCount, data.ReservationEnabled, data.MinimumStorageDays, data.CleaningFee, data.RepairFee, data.TowingFee, data.OverdueStorageFee, data.HazardousSurcharge, data.SpecialHandlingFee, data.ReviewLevel, data.Meta, data.Id)
	return err
}

func (m *defaultDepotsModel) tableName() string {
	return m.table
}
