// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package treenodes

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	treeNodesFieldNames          = builder.RawFieldNames(&TreeNodes{})
	treeNodesRows                = strings.Join(treeNodesFieldNames, ",")
	treeNodesRowsExpectAutoSet   = strings.Join(stringx.Remove(treeNodesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	treeNodesRowsWithPlaceHolder = strings.Join(stringx.Remove(treeNodesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	treeNodesModel interface {
		Insert(ctx context.Context, data *TreeNodes) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*TreeNodes, error)
		Update(ctx context.Context, data *TreeNodes) error
		Delete(ctx context.Context, id int64) error
	}

	defaultTreeNodesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	TreeNodes struct {
		Id            int64           `db:"id"`
		Name          sql.NullString  `db:"name"`
		Description   sql.NullString  `db:"description"`
		UserId        sql.NullInt64   `db:"user_id"`
		ObjectsCount  int64           `db:"objects_count"`
		Ancestry      sql.NullString  `db:"ancestry"`
		AncestryDepth sql.NullInt64   `db:"ancestry_depth"`
		Position      int64           `db:"position"`
		Status        int64           `db:"status"`
		Value         sql.NullString  `db:"value"`
		Visible       int64           `db:"visible"`
		ChildrenCount int64           `db:"children_count"`
		Data          sql.NullString  `db:"data"`
		CreatedAt     time.Time       `db:"created_at"`
		UpdatedAt     time.Time       `db:"updated_at"`
		Type          sql.NullString  `db:"type"`
		EnglishName   sql.NullString  `db:"english_name"`
		Extra         string          `db:"extra"`
		Lat           sql.NullFloat64 `db:"lat"`
		Lng           sql.NullFloat64 `db:"lng"`
		Icon          sql.NullString  `db:"icon"`
		Level         int64           `db:"level"`
		Level1        sql.NullInt64   `db:"level1"`
		Level2        sql.NullInt64   `db:"level2"`
		Level3        sql.NullInt64   `db:"level3"`
		Level4        sql.NullInt64   `db:"level4"`
		Level5        sql.NullInt64   `db:"level5"`
		IsPrimary     int64           `db:"is_primary"`
		Meta          string          `db:"meta"`
		UsageCount    int64           `db:"usage_count"`
		Timezone      sql.NullString  `db:"timezone"`
		FullName      sql.NullString  `db:"full_name"`
		FullNameCn    sql.NullString  `db:"full_name_cn"`
		SearchText    sql.NullString  `db:"search_text"`
	}
)

func newTreeNodesModel(conn sqlx.SqlConn) *defaultTreeNodesModel {
	return &defaultTreeNodesModel{
		conn:  conn,
		table: "`tree_nodes`",
	}
}

func (m *defaultTreeNodesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultTreeNodesModel) FindOne(ctx context.Context, id int64) (*TreeNodes, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", treeNodesRows, m.table)
	var resp TreeNodes
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTreeNodesModel) Insert(ctx context.Context, data *TreeNodes) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, treeNodesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.UserId, data.ObjectsCount, data.Ancestry, data.AncestryDepth, data.Position, data.Status, data.Value, data.Visible, data.ChildrenCount, data.Data, data.Type, data.EnglishName, data.Extra, data.Lat, data.Lng, data.Icon, data.Level, data.Level1, data.Level2, data.Level3, data.Level4, data.Level5, data.IsPrimary, data.Meta, data.UsageCount, data.Timezone, data.FullName, data.FullNameCn, data.SearchText)
	return ret, err
}

func (m *defaultTreeNodesModel) Update(ctx context.Context, data *TreeNodes) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, treeNodesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Description, data.UserId, data.ObjectsCount, data.Ancestry, data.AncestryDepth, data.Position, data.Status, data.Value, data.Visible, data.ChildrenCount, data.Data, data.Type, data.EnglishName, data.Extra, data.Lat, data.Lng, data.Icon, data.Level, data.Level1, data.Level2, data.Level3, data.Level4, data.Level5, data.IsPrimary, data.Meta, data.UsageCount, data.Timezone, data.FullName, data.FullNameCn, data.SearchText, data.Id)
	return err
}

func (m *defaultTreeNodesModel) tableName() string {
	return m.table
}
