// Code generated by hand to match goctl style.
package enums

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	enumsFieldNames          = builder.RawFieldNames(&Enums{})
	enumsRows                = strings.Join(enumsFieldNames, ",")
	enumsRowsExpectAutoSet   = strings.Join(stringx.Remove(enumsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	enumsRowsWithPlaceHolder = strings.Join(stringx.Remove(enumsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	enumsModel interface {
		Insert(ctx context.Context, data *Enums) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Enums, error)
		Update(ctx context.Context, data *Enums) error
		Delete(ctx context.Context, id int64) error
	}

	defaultEnumsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	// Enums 对应 enums 数据表中的一行数据。
	Enums struct {
		Id            int64     `db:"id"`
		Category      string    `db:"category"`
		CategoryName  string    `db:"category_name"`
		ItemId        string    `db:"item_id"`
		Value         string    `db:"value"`
		Name          string    `db:"name"`
		NameZh        string    `db:"name_zh"`
		Description   string    `db:"description"`
		DescriptionZh string    `db:"description_zh"`
		Extra         string    `db:"extra"`
		CreatedAt     time.Time `db:"created_at"`
		UpdatedAt     time.Time `db:"updated_at"`
	}
)

func newEnumsModel(conn sqlx.SqlConn) *defaultEnumsModel {
	return &defaultEnumsModel{
		conn:  conn,
		table: "`enums`",
	}
}

func (m *defaultEnumsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultEnumsModel) FindOne(ctx context.Context, id int64) (*Enums, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", enumsRows, m.table)
	var resp Enums
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultEnumsModel) Insert(ctx context.Context, data *Enums) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, enumsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Category, data.CategoryName, data.ItemId, data.Value, data.Name, data.NameZh, data.Description, data.DescriptionZh, data.Extra)
	return ret, err
}

func (m *defaultEnumsModel) Update(ctx context.Context, data *Enums) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, enumsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Category, data.CategoryName, data.ItemId, data.Value, data.Name, data.NameZh, data.Description, data.DescriptionZh, data.Extra, data.Id)
	return err
}

func (m *customEnumsModel) FindOneByCategoryAndValue(ctx context.Context, category, value string) (*Enums, error) {
	query := fmt.Sprintf("select %s from %s where `category` = ? and `value` = ? limit 1", enumsRows, m.table)
	var resp Enums
	err := m.conn.QueryRowCtx(ctx, &resp, query, category, value)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *customEnumsModel) FindByCategoryAndItemIds(ctx context.Context, category string, itemIds []string) ([]*Enums, error) {
	if len(itemIds) == 0 {
		return nil, nil
	}
	placeholders := make([]string, len(itemIds))
	args := make([]interface{}, 0, len(itemIds)+1)
	args = append(args, category)
	for i, id := range itemIds {
		placeholders[i] = "?"
		args = append(args, id)
	}
	query := fmt.Sprintf("select %s from %s where `category` = ? and `item_id` in (%s)", enumsRows, m.table, strings.Join(placeholders, ","))
	var resp []*Enums
	err := m.conn.QueryRowsCtx(ctx, &resp, query, args...)
	return resp, err
}

func (m *customEnumsModel) FindByCategories(ctx context.Context, categories []string) ([]*Enums, error) {
	if len(categories) == 0 {
		query := fmt.Sprintf("select %s from %s", enumsRows, m.table)
		var resp []*Enums
		err := m.conn.QueryRowsCtx(ctx, &resp, query)
		return resp, err
	}
	placeholders := make([]string, len(categories))
	args := make([]interface{}, len(categories))
	for i, cat := range categories {
		placeholders[i] = "?"
		args[i] = cat
	}
	query := fmt.Sprintf("select %s from %s where `category` in (%s)", enumsRows, m.table, strings.Join(placeholders, ","))
	var resp []*Enums
	err := m.conn.QueryRowsCtx(ctx, &resp, query, args...)
	return resp, err
}
