// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package offers

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	offersFieldNames          = builder.RawFieldNames(&Offers{})
	offersRows                = strings.Join(offersFieldNames, ",")
	offersRowsExpectAutoSet   = strings.Join(stringx.Remove(offersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	offersRowsWithPlaceHolder = strings.Join(stringx.Remove(offersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	offersModel interface {
		Insert(ctx context.Context, data *Offers) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Offers, error)
		Update(ctx context.Context, data *Offers) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOffersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Offers struct {
		Id                             int64           `db:"id"`
		Condition                      sql.NullInt64   `db:"condition"`
		Type                           string          `db:"type"`
		PickupLocationId               sql.NullInt64   `db:"pickup_location_id"`
		DropoffLocationId              sql.NullInt64   `db:"dropoff_location_id"`
		Quantity                       int64           `db:"quantity"`
		PickupCharge                   float64         `db:"pickup_charge"`
		FreeDays                       sql.NullInt64   `db:"free_days"`
		PerDiems                       float64         `db:"per_diems"`
		StorageFee                     float64         `db:"storage_fee"`
		Dpp                            float64         `db:"dpp"`
		Premium                        float64         `db:"premium"`
		NewBuildPrice                  float64         `db:"new_build_price"`
		DepreciationPerYear            float64         `db:"depreciation_per_year"`
		MinimumReplacementValue        float64         `db:"minimum_replacement_value"`
		AdditionalInformation          sql.NullString  `db:"additional_information"`
		UserId                         int64           `db:"user_id"`
		CompanyId                      sql.NullInt64   `db:"company_id"`
		Direction                      sql.NullInt64   `db:"direction"`
		ValidDays                      int64           `db:"valid_days"`
		EquipmentType                  int64           `db:"equipment_type"`
		CommercialTerm                 int64           `db:"commercial_term"`
		Comments                       sql.NullString  `db:"comments"`
		ReviewsCount                   int64           `db:"reviews_count"`
		Prefixes                       sql.NullString  `db:"prefixes"`
		YearOfManufacture              sql.NullInt64   `db:"year_of_manufacture"`
		ManufacturerId                 sql.NullInt64   `db:"manufacturer_id"`
		DamageProtectionPlan           float64         `db:"damage_protection_plan"`
		NegotiationsCount              int64           `db:"negotiations_count"`
		Category                       sql.NullInt64   `db:"category"`
		ExpiresAt                      sql.NullTime    `db:"expires_at"`
		ReviewId                       sql.NullInt64   `db:"review_id"`
		Detail                         sql.NullString  `db:"detail"`
		Status                         int64           `db:"status"`
		DeletedAt                      sql.NullTime    `db:"deleted_at"`
		ExpiresIn                      int64           `db:"expires_in"`
		ReadyForPickupOn               sql.NullTime    `db:"ready_for_pickup_on"`
		ReadyForPickupFrom             sql.NullTime    `db:"ready_for_pickup_from"`
		ReadyForPickupTo               sql.NullTime    `db:"ready_for_pickup_to"`
		WithLockBox                    int64           `db:"with_lock_box"`
		WithForkliftPockets            int64           `db:"with_forklift_pockets"`
		SellFor                        sql.NullInt64   `db:"sell_for"`
		LocationId                     sql.NullInt64   `db:"location_id"`
		Name                           sql.NullString  `db:"name"`
		ImagesCount                    int64           `db:"images_count"`
		DocumentsCount                 int64           `db:"documents_count"`
		TradeType                      int64           `db:"trade_type"`
		ExpectedDeliveryOn             sql.NullTime    `db:"expected_delivery_on"`
		ExpectedDeliveryFrom           sql.NullTime    `db:"expected_delivery_from"`
		ExpectedDeliveryTo             sql.NullTime    `db:"expected_delivery_to"`
		DepotId                        sql.NullInt64   `db:"depot_id"`
		UniqueNumber                   sql.NullString  `db:"unique_number"`
		CreatedAt                      time.Time       `db:"created_at"`
		UpdatedAt                      time.Time       `db:"updated_at"`
		Price                          sql.NullFloat64 `db:"price"`
		Color                          sql.NullInt64   `db:"color"`
		EstimatedEmptyDeliveryDateFrom sql.NullTime    `db:"estimated_empty_delivery_date_from"`
		OfferType                      sql.NullInt64   `db:"offer_type"`
		Source                         int64           `db:"source"` // 来源
		PickupChargePayer              sql.NullInt64   `db:"pickup_charge_payer"`
		InsuranceFee                   float64         `db:"insurance_fee"`
		YearOfManufactureRangeFrom     sql.NullInt64   `db:"year_of_manufacture_range_from"`
		YearOfManufactureRangeTo       sql.NullInt64   `db:"year_of_manufacture_range_to"`
		CscTestCertificate             int64           `db:"csc_test_certificate"`
		EquipmentTypeId                sql.NullInt64   `db:"equipment_type_id"`
		InsuranceType                  sql.NullInt64   `db:"insurance_type"`
		InsuranceDays                  int64           `db:"insurance_days"`
		Extra                          sql.NullString  `db:"extra"`
		Colors                         sql.NullString  `db:"colors"`
		PinnedAt                       sql.NullTime    `db:"pinned_at"`
		BumpedAt                       sql.NullTime    `db:"bumped_at"`
		StorageFreeDays                int64           `db:"storage_free_days"`
		ConditionTagIds                sql.NullString  `db:"condition_tag_ids"`
		ConditionLogo                  sql.NullInt64   `db:"condition_logo"`
		NumberOfVents                  int64           `db:"number_of_vents"`
		DealCount                      int64           `db:"deal_count"`
		CscExpiresOn                   sql.NullTime    `db:"csc_expires_on"`
		EstimatedEmptyDeliveryDateTo   sql.NullTime    `db:"estimated_empty_delivery_date_to"`
		InstantSale                    int64           `db:"instant_sale"`
		ConsignorId                    sql.NullInt64   `db:"consignor_id"`
		ConsignorName                  sql.NullString  `db:"consignor_name"`
		Label                          sql.NullString  `db:"label"` // 标签
		DropoffLocationIds             sql.NullString  `db:"dropoff_location_ids"`
		PickupLocationIds              sql.NullString  `db:"pickup_location_ids"`
		OriginalPrice                  sql.NullFloat64 `db:"original_price"`
		IsSpecialOffer                 sql.NullInt64   `db:"is_special_offer"`
		SourceProposalId               sql.NullInt64   `db:"source_proposal_id"`
		IsExpired                      int64           `db:"is_expired"`
		DataSource                     int64           `db:"data_source"` // 数据来源: 0-fixture, 1-user
		Meta                           sql.NullString  `db:"meta"`
		IsNonNegotiable                int64           `db:"is_non_negotiable"`
		HasDamages                     int64           `db:"has_damages"`
		WithEasyOpenDoor               sql.NullInt64   `db:"with_easy_open_door"`
		AttachmentsCache               string          `db:"attachments_cache"`
	}
)

func newOffersModel(conn sqlx.SqlConn) *defaultOffersModel {
	return &defaultOffersModel{
		conn:  conn,
		table: "`offers`",
	}
}

func (m *defaultOffersModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultOffersModel) FindOne(ctx context.Context, id int64) (*Offers, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", offersRows, m.table)
	var resp Offers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOffersModel) Insert(ctx context.Context, data *Offers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, offersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Condition, data.Type, data.PickupLocationId, data.DropoffLocationId, data.Quantity, data.PickupCharge, data.FreeDays, data.PerDiems, data.StorageFee, data.Dpp, data.Premium, data.NewBuildPrice, data.DepreciationPerYear, data.MinimumReplacementValue, data.AdditionalInformation, data.UserId, data.CompanyId, data.Direction, data.ValidDays, data.EquipmentType, data.CommercialTerm, data.Comments, data.ReviewsCount, data.Prefixes, data.YearOfManufacture, data.ManufacturerId, data.DamageProtectionPlan, data.NegotiationsCount, data.Category, data.ExpiresAt, data.ReviewId, data.Detail, data.Status, data.DeletedAt, data.ExpiresIn, data.ReadyForPickupOn, data.ReadyForPickupFrom, data.ReadyForPickupTo, data.WithLockBox, data.WithForkliftPockets, data.SellFor, data.LocationId, data.Name, data.ImagesCount, data.DocumentsCount, data.TradeType, data.ExpectedDeliveryOn, data.ExpectedDeliveryFrom, data.ExpectedDeliveryTo, data.DepotId, data.UniqueNumber, data.Price, data.Color, data.EstimatedEmptyDeliveryDateFrom, data.OfferType, data.Source, data.PickupChargePayer, data.InsuranceFee, data.YearOfManufactureRangeFrom, data.YearOfManufactureRangeTo, data.CscTestCertificate, data.EquipmentTypeId, data.InsuranceType, data.InsuranceDays, data.Extra, data.Colors, data.PinnedAt, data.BumpedAt, data.StorageFreeDays, data.ConditionTagIds, data.ConditionLogo, data.NumberOfVents, data.DealCount, data.CscExpiresOn, data.EstimatedEmptyDeliveryDateTo, data.InstantSale, data.ConsignorId, data.ConsignorName, data.Label, data.DropoffLocationIds, data.PickupLocationIds, data.OriginalPrice, data.IsSpecialOffer, data.SourceProposalId, data.IsExpired, data.DataSource, data.Meta, data.IsNonNegotiable, data.HasDamages, data.WithEasyOpenDoor, data.AttachmentsCache)
	return ret, err
}

func (m *defaultOffersModel) Update(ctx context.Context, data *Offers) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, offersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Condition, data.Type, data.PickupLocationId, data.DropoffLocationId, data.Quantity, data.PickupCharge, data.FreeDays, data.PerDiems, data.StorageFee, data.Dpp, data.Premium, data.NewBuildPrice, data.DepreciationPerYear, data.MinimumReplacementValue, data.AdditionalInformation, data.UserId, data.CompanyId, data.Direction, data.ValidDays, data.EquipmentType, data.CommercialTerm, data.Comments, data.ReviewsCount, data.Prefixes, data.YearOfManufacture, data.ManufacturerId, data.DamageProtectionPlan, data.NegotiationsCount, data.Category, data.ExpiresAt, data.ReviewId, data.Detail, data.Status, data.DeletedAt, data.ExpiresIn, data.ReadyForPickupOn, data.ReadyForPickupFrom, data.ReadyForPickupTo, data.WithLockBox, data.WithForkliftPockets, data.SellFor, data.LocationId, data.Name, data.ImagesCount, data.DocumentsCount, data.TradeType, data.ExpectedDeliveryOn, data.ExpectedDeliveryFrom, data.ExpectedDeliveryTo, data.DepotId, data.UniqueNumber, data.Price, data.Color, data.EstimatedEmptyDeliveryDateFrom, data.OfferType, data.Source, data.PickupChargePayer, data.InsuranceFee, data.YearOfManufactureRangeFrom, data.YearOfManufactureRangeTo, data.CscTestCertificate, data.EquipmentTypeId, data.InsuranceType, data.InsuranceDays, data.Extra, data.Colors, data.PinnedAt, data.BumpedAt, data.StorageFreeDays, data.ConditionTagIds, data.ConditionLogo, data.NumberOfVents, data.DealCount, data.CscExpiresOn, data.EstimatedEmptyDeliveryDateTo, data.InstantSale, data.ConsignorId, data.ConsignorName, data.Label, data.DropoffLocationIds, data.PickupLocationIds, data.OriginalPrice, data.IsSpecialOffer, data.SourceProposalId, data.IsExpired, data.DataSource, data.Meta, data.IsNonNegotiable, data.HasDamages, data.WithEasyOpenDoor, data.AttachmentsCache, data.Id)
	return err
}

func (m *defaultOffersModel) tableName() string {
	return m.table
}
